### ISSUE TITLE
Error when start containers

### ISSUE THREAD

**Issue by BrunIF** [taichunmin/docker-serveo#1]
root@ssh-tunnel:~/serveo# docker-compose up 
Creating network "serveo_default" with the default driver
Creating serveo_nginx_1  ... done
Creating serveo_serveo_1 ... done
Attaching to serveo_nginx_1, serveo_serveo_1
serveo_1  | Warning: Permanently added 'serveo.otherhost.com,88.88.77.77' (ECDSA) to the list of known hosts.
serveo_1  | Permission denied (publickey).
serveo_serveo_1 exited with code 255

**Comment by mahlingam** [comment]
ssh: Could not resolve hostname serveo.net: Name or service not known

Has serveo.net been shutdown today?

**Comment by BrunIF** [comment]
No. I use my domain name. 
p.s. two days site servero.net not working =(

**Comment by BrunIF** [comment]
when I change to:
```version: '2'

services:
  serveo:
    image: taichunmin/serveo:latest
    tty: true
    stdin_open: true
    # see https://serveo.net/ for more options
    command: "ssh -R 80:nginx:80 -o \"StrictHostKeyChecking no\" ssh.tenants.co"
    volumes:
      - ~/.ssh:/root/.ssh
  nginx:
    image: nginx:latest
    volumes: 
      - ~/.ssh:/root/.ssh
```
got next error
![screenshot from 2018-09-19 23 33 00](https://user-images.githubusercontent.com/490917/45779742-82158500-bc64-11e8-9e3f-cdfcd003cddd.png)

**Comment by BrunIF** [comment]
when I added my pub key to authorized_keys file containers start.
But how now create tunnel?

**Comment by BrunIF** [comment]
serveo.net is working now. And I understand where I was wrong.
